const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.EightDir.Cnds.IsMoving
	];
};
self.C3_JsPropNameTable = [
	{bg_cuca: 0},
	{bg_menu: 0},
	{titulo: 0},
	{bt_start: 0},
	{Mouse: 0},
	{bg_levels: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Plataforma: 0},
	{Sprite6: 0},
	{Teclado: 0},
	{Sprite5: 0},
	{chao_cuca2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sólido: 0},
	{Sensor_solido: 0},
	{Física: 0},
	{caldeirao_cuca: 0},
	{diamante: 0},
	{Cuca: 0},
	{direcao: 0},
	{morcego_sprite: 0},
	{Sensor_Direita: 0},
	{Sensor_Esquerda: 0},
	{caixa_element: 0},
	{bg_saci: 0},
	{portal_saida: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{bg_iara: 0},
	{escada_elemento: 0},
	{Sprite11: 0},
	{element_escada: 0},
	{diamante_vermelho: 0},
	{Sprite12: 0},
	{"8Direções": 0},
	{Sprite13: 0},
	{diamanteiara: 0},
	{ramoVermelho: 0},
	{ramoVerde: 0},
	{ramoverde2: 0},
	{ramoVermelhoP: 0},
	{portao: 0},
	{Sprite14: 0},
	{portalNovo: 0},
	{vida: 0}
];

self.InstanceType = {
	bg_cuca: class extends self.ISpriteInstance {},
	bg_menu: class extends self.ISpriteInstance {},
	titulo: class extends self.ISpriteInstance {},
	bt_start: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bg_levels: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	chao_cuca2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sensor_solido: class extends self.ISpriteInstance {},
	caldeirao_cuca: class extends self.ISpriteInstance {},
	diamante: class extends self.ISpriteInstance {},
	Cuca: class extends self.ISpriteInstance {},
	morcego_sprite: class extends self.ISpriteInstance {},
	Sensor_Direita: class extends self.ISpriteInstance {},
	Sensor_Esquerda: class extends self.ISpriteInstance {},
	caixa_element: class extends self.ISpriteInstance {},
	bg_saci: class extends self.ISpriteInstance {},
	portal_saida: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	bg_iara: class extends self.ISpriteInstance {},
	escada_elemento: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	element_escada: class extends self.ISpriteInstance {},
	diamante_vermelho: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	diamanteiara: class extends self.ISpriteInstance {},
	ramoVermelho: class extends self.ISpriteInstance {},
	ramoVerde: class extends self.ISpriteInstance {},
	ramoverde2: class extends self.ISpriteInstance {},
	ramoVermelhoP: class extends self.ISpriteInstance {},
	portao: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	portalNovo: class extends self.ISpriteInstance {}
}